apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nginx
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.i544c.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-nginx
                port:
                  number: 80
  tls:
    - hosts:
      - k8s.i544c.me
      secretName: k8s-i544c-me
