apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: vrc@i544c.me
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-i544c-me
  namespace: default
spec:
  secretName: k8s-i544c-me
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  commonName: k8s.i544c.me
  dnsNames:
  - k8s.i544c.me
  - "*.k8s.i544c.me"

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager # NOTE: cert-manager から参照する必要があるため
spec:
  encryptedData:
    api-token: AgBHC0d+xvB04ScFX8g79AX82+2IP8p1m5qFLg1OSUK3nmunbUKI0WYgqNsXyHBb28wSIsHh0vTjR6s0rV5g03/bjsYQXXq7wUT3hjx1Ele2krb0hZHdp9K9sXpK30d+aiS2zuggMFGfWYGZO0psJiaCJnyJlmSY2PZ/EMyOIHdXDbVHBDmcxDGbcCDE8aB5lXFE0RCKwGPSJDKgrlKG34EMCVxFhw8PGPE3Y/H/DTmZd+L5Tk3zJAEL1FDSAvu4Mb0NaHDdj4k4DddhKOU6HGsQg0Eo96V1WPwKbTmgCyZHK5y6nepAboBwx1h168y4LmsLoiSF7XPf7SqU0mor8Rv6FH72zE5aFjOAWPYUlelgO4qQhovUKbZ+LW/frkIr61ldquJXA22iuGpy26oY8BnQLuzzTFqA4qh2ouo26moe/JzD3nwVw7OcglwsbmAKZzfEFBMy22a/eJcfGQkA2vSFqze6Kq9UN8x7q58JuP06VmfXKFw1MqNZJiwP0lDA0IqWqYnpcgThpqrnkx/cTcgZHCAaXg87pxHt6lmbi6xW9hqjUnhdWhPhhENZ/mJDwZ/wMlC9/XF7iRuOnT9CAZIbbMewSBJBuuBKcX+Vz+6e/dYXq4ZpJh+w4cAEi5s6s2UKv+PZPSSllDwE9kwgU5qXFPL/fMzS8VM1IqiuWVOteLCISDzP9Ut81mS2hQizkyCkr0rfD0Wb8oBMQDv54aKs4CbpO/xdhROQigcLVINrr50whjjYup/u
